version: '3.2'

services:
  tester:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
    - .:/app    
    - ./.aws:/root/.aws    

  aws:
    build:
      context: .
      dockerfile: Dockerfile-aws
    working_dir: /app
    volumes:
    - .:/app    
    - ./.aws:/root/.aws     